In [1]:
import pandas as pd
import numpy as np

DATA_PATH = "../data/raw/data.csv"

df = pd.read_csv(DATA_PATH)

print("Original shape:", df.shape)

Original shape: (541909, 8)

In [2]:
clean_df = df.copy()

print("Working dataset shape:", clean_df.shape)

Working dataset shape: (541909, 8)

In [3]:
cancelled_mask = clean_df["InvoiceNo"].astype(str).str.startswith("C")
negative_quantity_mask = clean_df["Quantity"] < 0

print("Cancelled rows:", cancelled_mask.sum())
print("Negative quantity rows:", negative_quantity_mask.sum())

print(
    "Cancelled + negative quantity:",
    (cancelled_mask & negative_quantity_mask).sum()
)

print(
    "Negative quantity but NOT cancelled:",
    (~cancelled_mask & negative_quantity_mask).sum()
)

Cancelled rows: 9288
Negative quantity rows: 10624
Cancelled + negative quantity: 9288
Negative quantity but NOT cancelled: 1336

In [4]:
remaining_negative = clean_df[
    (~cancelled_mask) & negative_quantity_mask
]

remaining_negative.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,12/1/2010 16:50,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,12/2/2010 14:42,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,12/3/2010 15:30,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,12/3/2010 15:30,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,12/3/2010 15:30,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,12/3/2010 15:32,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,12/3/2010 15:33,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,12/3/2010 15:33,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,12/3/2010 15:34,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,12/3/2010 15:35,0.0,NaN,United Kingdom
7198,537006,21648,NaN,-130,12/3/2010 15:36,0.0,NaN,United Kingdom
7199,537007,21172,NaN,-80,12/3/2010 15:36,0.0,NaN,United Kingdom
7200,537008,21161,NaN,-120,12/3/2010 15:37,0.0,NaN,United Kingdom
7201,537009,84534B,NaN,-80,12/3/2010 15:38,0.0,NaN,United Kingdom
7202,537010,22162,NaN,-40,12/3/2010 15:38,0.0,NaN,United Kingdom
7203,537011,22139,NaN,-5,12/3/2010 15:38,0.0,NaN,United Kingdom
7204,537012,21535,NaN,-12,12/3/2010 15:39,0.0,NaN,United Kingdom
7205,537013,35965,NaN,-25,12/3/2010 15:40,0.0,NaN,United Kingdom
7206,537014,21040,NaN,-20,12/3/2010 15:40,0.0,NaN,United Kingdom
7207,537015,37464,NaN,-14,12/3/2010 15:41,0.0,NaN,United Kingdom

In [5]:
print("Remaining negative-quantity rows:",
      len(remaining_negative))

print(
    "Unique invoices:",
    remaining_negative["InvoiceNo"].nunique()
)

print(
    "Unique customers:",
    remaining_negative["CustomerID"].nunique()
)

print(
    "Total negative quantity:",
    remaining_negative["Quantity"].sum()
)

print(
    "Total negative transaction value:",
    (remaining_negative["Quantity"] *
     remaining_negative["UnitPrice"]).sum()
)

Remaining negative-quantity rows: 1336
Unique invoices: 1336
Unique customers: 0
Total negative quantity: -206957
Total negative transaction value: 0.0

In [6]:
remaining_negative[[
    "InvoiceNo",
    "StockCode",
    "Description",
    "Quantity",
    "InvoiceDate",
    "UnitPrice",
    "CustomerID",
    "Country"
]].head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,12/1/2010 16:50,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,12/2/2010 14:42,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,12/3/2010 15:30,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,12/3/2010 15:30,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,12/3/2010 15:30,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,12/3/2010 15:32,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,12/3/2010 15:33,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,12/3/2010 15:33,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,12/3/2010 15:34,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,12/3/2010 15:35,0.0,NaN,United Kingdom
7198,537006,21648,NaN,-130,12/3/2010 15:36,0.0,NaN,United Kingdom
7199,537007,21172,NaN,-80,12/3/2010 15:36,0.0,NaN,United Kingdom
7200,537008,21161,NaN,-120,12/3/2010 15:37,0.0,NaN,United Kingdom
7201,537009,84534B,NaN,-80,12/3/2010 15:38,0.0,NaN,United Kingdom
7202,537010,22162,NaN,-40,12/3/2010 15:38,0.0,NaN,United Kingdom
7203,537011,22139,NaN,-5,12/3/2010 15:38,0.0,NaN,United Kingdom
7204,537012,21535,NaN,-12,12/3/2010 15:39,0.0,NaN,United Kingdom
7205,537013,35965,NaN,-25,12/3/2010 15:40,0.0,NaN,United Kingdom
7206,537014,21040,NaN,-20,12/3/2010 15:40,0.0,NaN,United Kingdom
7207,537015,37464,NaN,-14,12/3/2010 15:41,0.0,NaN,United Kingdom

In [7]:
negative_with_customer = clean_df[
    (clean_df["Quantity"] < 0) &
    (clean_df["CustomerID"].notna())
]

print("Negative quantity rows with valid CustomerID:",
      len(negative_with_customer))

Negative quantity rows with valid CustomerID: 8905

In [8]:
print(
    "Negative quantity rows with valid CustomerID and positive UnitPrice:",
    len(
        clean_df[
            (clean_df["Quantity"] < 0) &
            (clean_df["CustomerID"].notna()) &
            (clean_df["UnitPrice"] > 0)
        ]
    )
)

Negative quantity rows with valid CustomerID and positive UnitPrice: 8905

In [9]:
negative_valid_customer = clean_df[
    (clean_df["Quantity"] < 0) &
    (clean_df["CustomerID"].notna()) &
    (clean_df["UnitPrice"] > 0)
]

negative_valid_customer[
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "InvoiceDate",
        "UnitPrice",
        "CustomerID",
        "Country"
    ]
].head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,12/1/2010 9:41,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,12/1/2010 9:49,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,12/1/2010 10:24,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,12/1/2010 10:24,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,12/1/2010 10:24,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,12/1/2010 10:24,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,12/1/2010 12:38,4.25,17897.0,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,-1,12/1/2010 14:30,2.10,17841.0,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,12/1/2010 14:30,0.85,17841.0,United Kingdom
1973,C536548,22244,3 HOOK HANGER MAGIC GARDEN,-4,12/1/2010 14:33,1.95,12472.0,Germany
1974,C536548,22242,5 HOOK HANGER MAGIC TOADSTOOL,-5,12/1/2010 14:33,1.65,12472.0,Germany
1975,C536548,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-1,12/1/2010 14:33,2.95,12472.0,Germany
1976,C536548,22892,SET OF SALT AND PEPPER TOADSTOOLS,-7,12/1/2010 14:33,1.25,12472.0,Germany
1977,C536548,22654,DELUXE SEWING KIT,-1,12/1/2010 14:33,5.95,12472.0,Germany
1978,C536548,22767,TRIPLE PHOTO FRAME CORNICE,-2,12/1/2010 14:33,9.95,12472.0,Germany
1979,C536548,22333,RETROSPOT PARTY BAG + STICKER SET,-1,12/1/2010 14:33,1.65,12472.0,Germany
1980,C536548,22245,"HOOK, 1 HANGER ,MAGIC GARDEN",-2,12/1/2010 14:33,0.85,12472.0,Germany

In [10]:
print("Unique customers with negative transactions:",
      negative_valid_customer["CustomerID"].nunique())

print("Unique invoices:",
      negative_valid_customer["InvoiceNo"].nunique())

print("Total negative quantity:",
      negative_valid_customer["Quantity"].sum())

print("Total negative transaction value:",
      (negative_valid_customer["Quantity"] *
       negative_valid_customer["UnitPrice"]).sum())

Unique customers with negative transactions: 1589
Unique invoices: 3654
Total negative quantity: -274808
Total negative transaction value: -611342.0900000001

In [11]:
negative_valid_customer = clean_df[
    (clean_df["Quantity"] < 0) &
    (clean_df["CustomerID"].notna()) &
    (clean_df["UnitPrice"] > 0)
]

negative_valid_customer[
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "InvoiceDate",
        "UnitPrice",
        "CustomerID",
        "Country"
    ]
].head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,12/1/2010 9:41,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,12/1/2010 9:49,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,12/1/2010 10:24,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,12/1/2010 10:24,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,12/1/2010 10:24,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,12/1/2010 10:24,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,12/1/2010 12:38,4.25,17897.0,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,-1,12/1/2010 14:30,2.10,17841.0,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,12/1/2010 14:30,0.85,17841.0,United Kingdom
1973,C536548,22244,3 HOOK HANGER MAGIC GARDEN,-4,12/1/2010 14:33,1.95,12472.0,Germany
1974,C536548,22242,5 HOOK HANGER MAGIC TOADSTOOL,-5,12/1/2010 14:33,1.65,12472.0,Germany
1975,C536548,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-1,12/1/2010 14:33,2.95,12472.0,Germany
1976,C536548,22892,SET OF SALT AND PEPPER TOADSTOOLS,-7,12/1/2010 14:33,1.25,12472.0,Germany
1977,C536548,22654,DELUXE SEWING KIT,-1,12/1/2010 14:33,5.95,12472.0,Germany
1978,C536548,22767,TRIPLE PHOTO FRAME CORNICE,-2,12/1/2010 14:33,9.95,12472.0,Germany
1979,C536548,22333,RETROSPOT PARTY BAG + STICKER SET,-1,12/1/2010 14:33,1.65,12472.0,Germany
1980,C536548,22245,"HOOK, 1 HANGER ,MAGIC GARDEN",-2,12/1/2010 14:33,0.85,12472.0,Germany

In [12]:
print("Unique customers with negative transactions:",
      negative_valid_customer["CustomerID"].nunique())

print("Unique invoices:",
      negative_valid_customer["InvoiceNo"].nunique())

print("Total negative quantity:",
      negative_valid_customer["Quantity"].sum())

print("Total negative transaction value:",
      (negative_valid_customer["Quantity"] *
       negative_valid_customer["UnitPrice"]).sum())

Unique customers with negative transactions: 1589
Unique invoices: 3654
Total negative quantity: -274808
Total negative transaction value: -611342.0900000001

In [13]:
negative_valid_customer_cancelled = (
    negative_valid_customer["InvoiceNo"]
    .astype(str)
    .str.startswith("C")
)

print(
    "Negative transactions marked as cancelled:",
    negative_valid_customer_cancelled.sum()
)

print(
    "Negative transactions NOT marked as cancelled:",
    (~negative_valid_customer_cancelled).sum()
)

Negative transactions marked as cancelled: 8905
Negative transactions NOT marked as cancelled: 0

In [14]:
negative_valid_customer = clean_df[
    (clean_df["Quantity"] < 0) &
    (clean_df["CustomerID"].notna()) &
    (clean_df["UnitPrice"] > 0)
]

negative_valid_customer[
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "InvoiceDate",
        "UnitPrice",
        "CustomerID",
        "Country"
    ]
].head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,12/1/2010 9:41,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,12/1/2010 9:49,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,12/1/2010 10:24,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,12/1/2010 10:24,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,12/1/2010 10:24,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,12/1/2010 10:24,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,12/1/2010 12:38,4.25,17897.0,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,-1,12/1/2010 14:30,2.10,17841.0,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,12/1/2010 14:30,0.85,17841.0,United Kingdom
1973,C536548,22244,3 HOOK HANGER MAGIC GARDEN,-4,12/1/2010 14:33,1.95,12472.0,Germany
1974,C536548,22242,5 HOOK HANGER MAGIC TOADSTOOL,-5,12/1/2010 14:33,1.65,12472.0,Germany
1975,C536548,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-1,12/1/2010 14:33,2.95,12472.0,Germany
1976,C536548,22892,SET OF SALT AND PEPPER TOADSTOOLS,-7,12/1/2010 14:33,1.25,12472.0,Germany
1977,C536548,22654,DELUXE SEWING KIT,-1,12/1/2010 14:33,5.95,12472.0,Germany
1978,C536548,22767,TRIPLE PHOTO FRAME CORNICE,-2,12/1/2010 14:33,9.95,12472.0,Germany
1979,C536548,22333,RETROSPOT PARTY BAG + STICKER SET,-1,12/1/2010 14:33,1.65,12472.0,Germany
1980,C536548,22245,"HOOK, 1 HANGER ,MAGIC GARDEN",-2,12/1/2010 14:33,0.85,12472.0,Germany

In [15]:
print("Unique customers with negative transactions:",
      negative_valid_customer["CustomerID"].nunique())

print("Unique invoices:",
      negative_valid_customer["InvoiceNo"].nunique())

print("Total negative quantity:",
      negative_valid_customer["Quantity"].sum())

print("Total negative transaction value:",
      (negative_valid_customer["Quantity"] *
       negative_valid_customer["UnitPrice"]).sum())

Unique customers with negative transactions: 1589
Unique invoices: 3654
Total negative quantity: -274808
Total negative transaction value: -611342.0900000001

In [16]:
negative_valid_customer_cancelled = (
    negative_valid_customer["InvoiceNo"]
    .astype(str)
    .str.startswith("C")
)

print(
    "Negative transactions marked as cancelled:",
    negative_valid_customer_cancelled.sum()
)

print(
    "Negative transactions NOT marked as cancelled:",
    (~negative_valid_customer_cancelled).sum()
)

Negative transactions marked as cancelled: 8905
Negative transactions NOT marked as cancelled: 0

In [17]:
non_cancelled_df = clean_df[
    ~clean_df["InvoiceNo"].astype(str).str.startswith("C")
]

print("Rows after excluding cancelled invoices:", len(non_cancelled_df))
print("Negative quantities remaining:",
      (non_cancelled_df["Quantity"] < 0).sum())
print("Missing CustomerID remaining:",
      non_cancelled_df["CustomerID"].isna().sum())
print("Zero UnitPrice remaining:",
      (non_cancelled_df["UnitPrice"] == 0).sum())
print("Negative UnitPrice remaining:",
      (non_cancelled_df["UnitPrice"] < 0).sum())

Rows after excluding cancelled invoices: 532621
Negative quantities remaining: 1336
Missing CustomerID remaining: 134697
Zero UnitPrice remaining: 2515
Negative UnitPrice remaining: 2

In [18]:
negative_valid_customer[
    ["Quantity", "UnitPrice"]
].describe()

           Quantity     UnitPrice
count   8905.000000   8905.000000
mean     -30.859966     18.845519
std     1170.154939    444.366043
min   -80995.000000      0.010000
25%       -6.000000      1.450000
50%       -2.000000      2.950000
75%       -1.000000      4.950000
max       -1.000000  38970.000000

In [19]:
negative_valid_customer["CustomerID"].nunique()

1589

In [20]:
positive_transactions = clean_df[
    (clean_df["CustomerID"].notna()) &
    (clean_df["Quantity"] > 0) &
    (clean_df["UnitPrice"] > 0) &
    (~clean_df["InvoiceNo"].astype(str).str.startswith("C"))
].copy()

negative_transactions = clean_df[
    (clean_df["CustomerID"].notna()) &
    (clean_df["Quantity"] < 0) &
    (clean_df["UnitPrice"] > 0)
].copy()

In [21]:
positive_pairs = set(
    zip(
        positive_transactions["CustomerID"],
        positive_transactions["StockCode"]
    )
)

negative_transactions["has_positive_purchase"] = [
    (customer, stockcode) in positive_pairs
    for customer, stockcode in zip(
        negative_transactions["CustomerID"],
        negative_transactions["StockCode"]
    )
]

print(
    "Negative transactions with a corresponding "
    "customer-product positive purchase:",
    negative_transactions["has_positive_purchase"].sum()
)

print(
    "Negative transactions without a corresponding "
    "customer-product positive purchase:",
    (~negative_transactions["has_positive_purchase"]).sum()
)

Negative transactions with a corresponding customer-product positive purchase: 7957
Negative transactions without a corresponding customer-product positive purchase: 948

In [22]:
zero_price = clean_df[clean_df["UnitPrice"] == 0]

print("Zero-price rows:", len(zero_price))
print("Unique customers:", zero_price["CustomerID"].nunique())
print("Missing CustomerID:", zero_price["CustomerID"].isna().sum())
print("Negative quantity rows:", (zero_price["Quantity"] < 0).sum())
print("Positive quantity rows:", (zero_price["Quantity"] > 0).sum())

Zero-price rows: 2515
Unique customers: 31
Missing CustomerID: 2475
Negative quantity rows: 1336
Positive quantity rows: 1179

In [23]:
zero_price[
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "InvoiceDate",
        "UnitPrice",
        "CustomerID",
        "Country"
    ]
].head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,12/1/2010 11:52,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,12/1/2010 14:32,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,12/1/2010 14:33,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,12/1/2010 14:33,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,12/1/2010 14:34,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,12/1/2010 14:34,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,12/1/2010 14:34,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,12/1/2010 14:35,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,12/1/2010 14:35,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,12/1/2010 16:50,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,12/2/2010 14:42,0.0,NaN,United Kingdom
4348,536765,84952C,NaN,19,12/2/2010 14:43,0.0,NaN,United Kingdom
6391,536941,22734,amazon,20,12/3/2010 12:08,0.0,NaN,United Kingdom
6392,536942,22139,amazon,15,12/3/2010 12:08,0.0,NaN,United Kingdom
7187,536995,35951,NaN,57,12/3/2010 15:29,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,12/3/2010 15:30,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,12/3/2010 15:30,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,12/3/2010 15:30,0.0,NaN,United Kingdom
7191,536999,21421,NaN,110,12/3/2010 15:32,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,12/3/2010 15:32,0.0,NaN,United Kingdom

In [24]:
zero_price_with_customer = clean_df[
    (clean_df["UnitPrice"] == 0) &
    (clean_df["CustomerID"].notna())
]

print("Zero-price rows with CustomerID:",
      len(zero_price_with_customer))

print(
    "Positive quantity:",
    (zero_price_with_customer["Quantity"] > 0).sum()
)

print(
    "Negative quantity:",
    (zero_price_with_customer["Quantity"] < 0).sum()
)

zero_price_with_customer[
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "InvoiceDate",
        "UnitPrice",
        "CustomerID",
        "Country"
    ]
]

Zero-price rows with CustomerID: 40
Positive quantity: 40
Negative quantity: 0

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
9302,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,12/5/2010 14:02,0.0,12647.0,Germany
33576,539263,22580,ADVENT CALENDAR GINGHAM SACK,4,12/16/2010 14:36,0.0,16560.0,United Kingdom
40089,539722,22423,REGENCY CAKESTAND 3 TIER,10,12/21/2010 13:45,0.0,14911.0,EIRE
47068,540372,22090,PAPER BUNTING RETROSPOT,24,1/6/2011 16:41,0.0,13081.0,United Kingdom
47070,540372,22553,PLASTERS IN TIN SKULLS,24,1/6/2011 16:41,0.0,13081.0,United Kingdom
56674,541109,22168,ORGANISER WOOD ANTIQUE WHITE,1,1/13/2011 15:10,0.0,15107.0,United Kingdom
86789,543599,84535B,FAIRY CAKES NOTEBOOK A6 SIZE,16,2/10/2011 13:08,0.0,17560.0,United Kingdom
130188,547417,22062,CERAMIC BOWL WITH LOVE HEART DESIGN,36,3/23/2011 10:25,0.0,13239.0,United Kingdom
139453,548318,22055,MINI CAKE STAND HANGING STRAWBERY,5,3/30/2011 12:45,0.0,13113.0,United Kingdom
145208,548871,22162,HEART GARLAND RUSTIC PADDED,2,4/4/2011 14:42,0.0,14410.0,United Kingdom
157042,550188,22636,CHILDS BREAKFAST SET CIRCUS PARADE,1,4/14/2011 18:57,0.0,12457.0,Switzerland
187613,553000,47566,PARTY BUNTING,4,5/12/2011 15:21,0.0,17667.0,United Kingdom
198383,554037,22619,SET OF 6 SOLDIER SKITTLES,80,5/20/2011 14:13,0.0,12415.0,Australia
279324,561284,22167,OVAL WALL MIRROR DIAMANTE,1,7/26/2011 12:24,0.0,16818.0,United Kingdom
282912,561669,22960,JAM MAKING SET WITH JARS,11,7/28/2011 17:09,0.0,12507.0,Spain
285657,561916,M,Manual,1,8/1/2011 11:44,0.0,15581.0,United Kingdom
298054,562973,23157,SET OF 6 NATIVITY MAGNETS,240,8/11/2011 11:42,0.0,14911.0,EIRE
314745,564651,23270,SET OF 2 CERAMIC PAINTED HEARTS,96,8/26/2011 14:19,0.0,14646.0,Netherlands
314746,564651,23268,SET OF 2 CERAMIC CHRISTMAS REINDEER,192,8/26/2011 14:19,0.0,14646.0,Netherlands
314747,564651,22955,36 FOIL STAR CAKE CASES,144,8/26/2011 14:19,0.0,14646.0,Netherlands
314748,564651,21786,POLKADOT RAIN HAT,144,8/26/2011 14:19,0.0,14646.0,Netherlands
358655,568158,PADS,PADS TO MATCH ALL CUSHIONS,1,9/25/2011 12:22,0.0,16133.0,United Kingdom
361825,568384,M,Manual,1,9/27/2011 9:46,0.0,12748.0,United Kingdom
379913,569716,22778,GLASS CLOCHE SMALL,2,10/6/2011 8:17,0.0,15804.0,United Kingdom
395529,571035,M,Manual,1,10/13/2011 12:50,0.0,12446.0,RSA
420404,572893,21208,PASTEL COLOUR HONEYCOMB FAN,5,10/26/2011 14:36,0.0,18059.0,United Kingdom
436428,574138,23234,BISCUIT TIN VINTAGE CHRISTMAS,216,11/3/2011 11:26,0.0,12415.0,Australia
436597,574175,22065,CHRISTMAS PUDDING TRINKET POT,12,11/3/2011 11:47,0.0,14110.0,United Kingdom
436961,574252,M,Manual,1,11/3/2011 13:24,0.0,12437.0,France
439361,574469,22385,JUMBO BAG SPACEBOY DESIGN,12,11/4/2011 11:55,0.0,12431.0,Australia
446125,574879,22625,RED KITCHEN SCALES,2,11/7/2011 13:22,0.0,13014.0,United Kingdom
446793,574920,22899,CHILDREN'S APRON DOLLY GIRL,1,11/7/2011 16:34,0.0,13985.0,United Kingdom
446794,574920,23480,MINI LIGHTS WOODLAND MUSHROOMS,1,11/7/2011 16:34,0.0,13985.0,United Kingdom
454463,575579,22437,SET OF 9 BLACK SKULL BALLOONS,20,11/10/2011 11:49,0.0,13081.0,United Kingdom
454464,575579,22089,PAPER BUNTING VINTAGE PAISLEY,24,11/10/2011 11:49,0.0,13081.0,United Kingdom
479079,577129,22464,HANGING METAL HEART LANTERN,4,11/17/2011 19:52,0.0,15602.0,United Kingdom
479546,577168,M,Manual,1,11/18/2011 10:42,0.0,12603.0,Germany
480649,577314,23407,SET OF 2 TRAYS HOME SWEET HOME,2,11/18/2011 13:23,0.0,12444.0,Norway
485985,577696,M,Manual,1,11/21/2011 11:57,0.0,16406.0,United Kingdom
502122,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,11/25/2011 15:57,0.0,13256.0,United Kingdom

In [25]:
negative_price = clean_df[clean_df["UnitPrice"] < 0]

negative_price[
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "InvoiceDate",
        "UnitPrice",
        "CustomerID",
        "Country"
    ]
]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,8/12/2011 14:51,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,8/12/2011 14:52,-11062.06,NaN,United Kingdom

In [26]:
print("Negative-price rows:", len(negative_price))
print("Customers:", negative_price["CustomerID"].nunique())
print("Invoices:", negative_price["InvoiceNo"].nunique())

Negative-price rows: 2
Customers: 0
Invoices: 2

In [27]:
positive_quantity = clean_df[
    (clean_df["Quantity"] > 0) &
    (clean_df["UnitPrice"] > 0) &
    (clean_df["CustomerID"].notna()) &
    (~clean_df["InvoiceNo"].astype(str).str.startswith("C"))
]

positive_quantity.nlargest(
    20,
    "Quantity"
)[
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "InvoiceDate",
        "UnitPrice",
        "CustomerID",
        "Country"
    ]
]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,12/9/2011 9:15,2.08,16446.0,United Kingdom
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1/18/2011 10:01,1.04,12346.0,United Kingdom
421632,573008,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,4800,10/27/2011 12:26,0.21,12901.0,United Kingdom
206121,554868,22197,SMALL POPCORN HOLDER,4300,5/27/2011 10:52,0.72,13135.0,United Kingdom
97432,544612,22053,EMPIRE DESIGN ROSETTE,3906,2/22/2011 10:43,0.82,18087.0,United Kingdom
270885,560599,18007,ESSENTIAL BALM 3.5g TIN IN ENVELOPE,3186,7/19/2011 17:04,0.06,14609.0,United Kingdom
52711,540815,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,1/11/2011 12:55,2.10,15749.0,United Kingdom
160546,550461,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,4/18/2011 13:20,2.10,15749.0,United Kingdom
433788,573995,16014,SMALL CHINESE STYLE SCISSOR,3000,11/2/2011 11:24,0.32,16308.0,United Kingdom
4945,536830,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,2880,12/2/2010 17:38,0.18,16754.0,United Kingdom
291249,562439,84879,ASSORTED COLOUR BIRD ORNAMENT,2880,8/4/2011 18:06,1.45,12931.0,United Kingdom
201149,554272,21977,PACK OF 60 PINK PAISLEY CAKE CASES,2700,5/23/2011 13:08,0.42,12901.0,United Kingdom
80742,543057,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,2592,2/3/2011 10:50,0.21,16333.0,United Kingdom
32671,539101,22693,GROW A FLYTRAP OR SUNFLOWER IN TIN,2400,12/16/2010 10:35,0.94,16029.0,United Kingdom
87631,543669,22693,GROW A FLYTRAP OR SUNFLOWER IN TIN,2400,2/11/2011 11:22,0.94,16029.0,United Kingdom
91772,544152,18007,ESSENTIAL BALM 3.5g TIN IN ENVELOPE,2400,2/16/2011 12:10,0.06,14609.0,United Kingdom
421601,573003,23084,RABBIT NIGHT LIGHT,2400,10/27/2011 12:11,2.08,14646.0,Netherlands
125282,547037,21967,PACK OF 12 SKULL TISSUES,2160,3/20/2011 10:37,0.25,14101.0,United Kingdom
437480,574294,21915,RED HARMONICA IN BOX,2100,11/3/2011 15:47,1.06,16333.0,United Kingdom
511421,579498,23084,RABBIT NIGHT LIGHT,2040,11/29/2011 15:52,1.79,12798.0,Japan

In [28]:
positive_price = clean_df[
    (clean_df["Quantity"] > 0) &
    (clean_df["UnitPrice"] > 0) &
    (clean_df["CustomerID"].notna()) &
    (~clean_df["InvoiceNo"].astype(str).str.startswith("C"))
]

positive_price.nlargest(
    20,
    "UnitPrice"
)[
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "InvoiceDate",
        "UnitPrice",
        "CustomerID",
        "Country"
    ]
]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
173382,551697,POST,POSTAGE,1,5/3/2011 13:46,8142.75,16029.0,United Kingdom
422351,573077,M,Manual,1,10/27/2011 14:13,4161.06,12536.0,France
422376,573080,M,Manual,1,10/27/2011 14:20,4161.06,12536.0,France
406406,571751,M,Manual,1,10/19/2011 11:18,3949.32,12744.0,Singapore
374542,569382,M,Manual,1,10/3/2011 16:44,3155.95,15502.0,United Kingdom
297438,562946,M,Manual,1,8/11/2011 9:38,2500.00,15581.0,United Kingdom
144826,548813,M,Manual,1,4/4/2011 13:03,2382.92,12744.0,Singapore
406407,571751,M,Manual,1,10/19/2011 11:18,2118.74,12744.0,Singapore
144829,548820,M,Manual,1,4/4/2011 13:04,2053.07,12744.0,Singapore
343000,566927,M,Manual,1,9/15/2011 15:20,2033.10,17846.0,United Kingdom
150615,549468,M,Manual,1,4/8/2011 14:27,1867.86,17940.0,United Kingdom
117054,546328,M,Manual,1,3/11/2011 10:19,1687.17,14911.0,EIRE
117055,546329,M,Manual,1,3/11/2011 10:22,1687.17,14911.0,EIRE
528082,580727,DOT,DOTCOM POSTAGE,1,12/5/2011 17:17,1599.26,14096.0,United Kingdom
508459,579196,DOT,DOTCOM POSTAGE,1,11/28/2011 15:54,1526.76,14096.0,United Kingdom
467436,576339,DOT,DOTCOM POSTAGE,1,11/14/2011 15:27,1500.36,14096.0,United Kingdom
494728,578270,DOT,DOTCOM POSTAGE,1,11/23/2011 13:39,1270.06,14096.0,United Kingdom
144828,548813,M,Manual,1,4/4/2011 13:03,1252.95,12744.0,Singapore
200745,554155,M,Manual,1,5/23/2011 11:26,1241.98,12757.0,Portugal
201553,554301,M,Manual,1,5/23/2011 14:46,1241.98,12757.0,Portugal

In [29]:
positive_quantity = clean_df[
    (clean_df["Quantity"] > 0) &
    (clean_df["UnitPrice"] > 0) &
    (clean_df["CustomerID"].notna()) &
    (~clean_df["InvoiceNo"].astype(str).str.startswith("C"))
]

positive_quantity.nlargest(
    20,
    "Quantity"
)[
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "InvoiceDate",
        "UnitPrice",
        "CustomerID",
        "Country"
    ]
]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,12/9/2011 9:15,2.08,16446.0,United Kingdom
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1/18/2011 10:01,1.04,12346.0,United Kingdom
421632,573008,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,4800,10/27/2011 12:26,0.21,12901.0,United Kingdom
206121,554868,22197,SMALL POPCORN HOLDER,4300,5/27/2011 10:52,0.72,13135.0,United Kingdom
97432,544612,22053,EMPIRE DESIGN ROSETTE,3906,2/22/2011 10:43,0.82,18087.0,United Kingdom
270885,560599,18007,ESSENTIAL BALM 3.5g TIN IN ENVELOPE,3186,7/19/2011 17:04,0.06,14609.0,United Kingdom
52711,540815,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,1/11/2011 12:55,2.10,15749.0,United Kingdom
160546,550461,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,4/18/2011 13:20,2.10,15749.0,United Kingdom
433788,573995,16014,SMALL CHINESE STYLE SCISSOR,3000,11/2/2011 11:24,0.32,16308.0,United Kingdom
4945,536830,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,2880,12/2/2010 17:38,0.18,16754.0,United Kingdom
291249,562439,84879,ASSORTED COLOUR BIRD ORNAMENT,2880,8/4/2011 18:06,1.45,12931.0,United Kingdom
201149,554272,21977,PACK OF 60 PINK PAISLEY CAKE CASES,2700,5/23/2011 13:08,0.42,12901.0,United Kingdom
80742,543057,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,2592,2/3/2011 10:50,0.21,16333.0,United Kingdom
32671,539101,22693,GROW A FLYTRAP OR SUNFLOWER IN TIN,2400,12/16/2010 10:35,0.94,16029.0,United Kingdom
87631,543669,22693,GROW A FLYTRAP OR SUNFLOWER IN TIN,2400,2/11/2011 11:22,0.94,16029.0,United Kingdom
91772,544152,18007,ESSENTIAL BALM 3.5g TIN IN ENVELOPE,2400,2/16/2011 12:10,0.06,14609.0,United Kingdom
421601,573003,23084,RABBIT NIGHT LIGHT,2400,10/27/2011 12:11,2.08,14646.0,Netherlands
125282,547037,21967,PACK OF 12 SKULL TISSUES,2160,3/20/2011 10:37,0.25,14101.0,United Kingdom
437480,574294,21915,RED HARMONICA IN BOX,2100,11/3/2011 15:47,1.06,16333.0,United Kingdom
511421,579498,23084,RABBIT NIGHT LIGHT,2040,11/29/2011 15:52,1.79,12798.0,Japan

In [30]:
positive_price = clean_df[
    (clean_df["Quantity"] > 0) &
    (clean_df["UnitPrice"] > 0) &
    (clean_df["CustomerID"].notna()) &
    (~clean_df["InvoiceNo"].astype(str).str.startswith("C"))
]

positive_price.nlargest(
    20,
    "UnitPrice"
)[
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "InvoiceDate",
        "UnitPrice",
        "CustomerID",
        "Country"
    ]
]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
173382,551697,POST,POSTAGE,1,5/3/2011 13:46,8142.75,16029.0,United Kingdom
422351,573077,M,Manual,1,10/27/2011 14:13,4161.06,12536.0,France
422376,573080,M,Manual,1,10/27/2011 14:20,4161.06,12536.0,France
406406,571751,M,Manual,1,10/19/2011 11:18,3949.32,12744.0,Singapore
374542,569382,M,Manual,1,10/3/2011 16:44,3155.95,15502.0,United Kingdom
297438,562946,M,Manual,1,8/11/2011 9:38,2500.00,15581.0,United Kingdom
144826,548813,M,Manual,1,4/4/2011 13:03,2382.92,12744.0,Singapore
406407,571751,M,Manual,1,10/19/2011 11:18,2118.74,12744.0,Singapore
144829,548820,M,Manual,1,4/4/2011 13:04,2053.07,12744.0,Singapore
343000,566927,M,Manual,1,9/15/2011 15:20,2033.10,17846.0,United Kingdom
150615,549468,M,Manual,1,4/8/2011 14:27,1867.86,17940.0,United Kingdom
117054,546328,M,Manual,1,3/11/2011 10:19,1687.17,14911.0,EIRE
117055,546329,M,Manual,1,3/11/2011 10:22,1687.17,14911.0,EIRE
528082,580727,DOT,DOTCOM POSTAGE,1,12/5/2011 17:17,1599.26,14096.0,United Kingdom
508459,579196,DOT,DOTCOM POSTAGE,1,11/28/2011 15:54,1526.76,14096.0,United Kingdom
467436,576339,DOT,DOTCOM POSTAGE,1,11/14/2011 15:27,1500.36,14096.0,United Kingdom
494728,578270,DOT,DOTCOM POSTAGE,1,11/23/2011 13:39,1270.06,14096.0,United Kingdom
144828,548813,M,Manual,1,4/4/2011 13:03,1252.95,12744.0,Singapore
200745,554155,M,Manual,1,5/23/2011 11:26,1241.98,12757.0,Portugal
201553,554301,M,Manual,1,5/23/2011 14:46,1241.98,12757.0,Portugal

In [31]:
extreme_quantity = clean_df[
    (clean_df["Quantity"] >= 70000)
]

extreme_quantity[
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "InvoiceDate",
        "UnitPrice",
        "CustomerID",
        "Country"
    ]
]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1/18/2011 10:01,1.04,12346.0,United Kingdom
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,12/9/2011 9:15,2.08,16446.0,United Kingdom

In [32]:
print("Transactions with Quantity >= 70000:",
      len(extreme_quantity))

Transactions with Quantity >= 70000: 2

In [33]:
special_codes = clean_df[
    clean_df["StockCode"].astype(str).isin(["POST", "DOT", "M"])
]

print("POST/DOT/M rows:", len(special_codes))
print("Unique customers:", special_codes["CustomerID"].nunique())
print("Total quantity:", special_codes["Quantity"].sum())
print("Total transaction value:",
      (special_codes["Quantity"] *
       special_codes["UnitPrice"]).sum())

POST/DOT/M rows: 2537
Unique customers: 627
Total quantity: 11224
Total transaction value: 203801.93

In [34]:
special_codes["StockCode"].value_counts()

StockCode
POST    1256
DOT      710
M        571
Name: count, dtype: int64

In [35]:
# Step 1: Remove exact duplicate transaction rows

before_duplicates = len(clean_df)

clean_df = clean_df.drop_duplicates().copy()

after_duplicates = len(clean_df)
duplicates_removed = before_duplicates - after_duplicates

print("Rows before:", before_duplicates)
print("Rows after:", after_duplicates)
print("Duplicate rows removed:", duplicates_removed)

Rows before: 541909
Rows after: 536641
Duplicate rows removed: 5268

In [36]:
# Step 2: Remove transactions without CustomerID

before_customerid = len(clean_df)

missing_customerid = clean_df["CustomerID"].isna().sum()

clean_df = clean_df[
    clean_df["CustomerID"].notna()
].copy()

after_customerid = len(clean_df)

print("Rows before:", before_customerid)
print("Missing CustomerID rows removed:", missing_customerid)
print("Rows after:", after_customerid)
print("Customers remaining:", clean_df["CustomerID"].nunique())

Rows before: 536641
Missing CustomerID rows removed: 135037
Rows after: 401604
Customers remaining: 4372

In [37]:
# Step 3: Remove cancelled invoices

before_cancelled = len(clean_df)

cancelled_mask = clean_df["InvoiceNo"].astype(str).str.startswith("C")
cancelled_removed = cancelled_mask.sum()

clean_df = clean_df[
    ~cancelled_mask
].copy()

after_cancelled = len(clean_df)

print("Rows before:", before_cancelled)
print("Cancelled rows removed:", cancelled_removed)
print("Rows after:", after_cancelled)
print("Customers remaining:", clean_df["CustomerID"].nunique())

Rows before: 401604
Cancelled rows removed: 8872
Rows after: 392732
Customers remaining: 4339

In [38]:
# Step 4: Remove negative-quantity transactions

before_negative = len(clean_df)

negative_mask = clean_df["Quantity"] < 0
negative_removed = negative_mask.sum()

clean_df = clean_df[
    clean_df["Quantity"] > 0
].copy()

after_negative = len(clean_df)

print("Rows before:", before_negative)
print("Negative-quantity rows removed:", negative_removed)
print("Rows after:", after_negative)
print("Customers remaining:", clean_df["CustomerID"].nunique())

Rows before: 392732
Negative-quantity rows removed: 0
Rows after: 392732
Customers remaining: 4339

In [40]:
clean_df["Quantity"] > 0

0         True
1         True
2         True
3         True
4         True
          ...
541904    True
541905    True
541906    True
541907    True
541908    True
Name: Quantity, Length: 392732, dtype: bool

In [41]:
# Step 4: Remove negative-quantity transactions

before_negative = len(clean_df)

negative_mask = clean_df["Quantity"] < 0
negative_removed = negative_mask.sum()

clean_df = clean_df[
    clean_df["Quantity"] > 0
].copy()

after_negative = len(clean_df)

print("Rows before:", before_negative)
print("Negative-quantity rows removed:", negative_removed)
print("Rows after:", after_negative)
print("Customers remaining:", clean_df["CustomerID"].nunique())

Rows before: 392732
Negative-quantity rows removed: 0
Rows after: 392732
Customers remaining: 4339

In [42]:
clean_df["Quantity"]

0          6
1          6
2          8
3          6
4          6
          ..
541904    12
541905     6
541906     4
541907     4
541908     3
Name: Quantity, Length: 392732, dtype: int64

In [43]:
# Step 4: Remove negative-quantity transactions

before_negative = len(clean_df)

negative_mask = clean_df["Quantity"] < 0
negative_removed = negative_mask.sum()

clean_df = clean_df[
    clean_df["Quantity"] > 0
].copy()

after_negative = len(clean_df)

print("Rows before:", before_negative)
print("Negative-quantity rows removed:", negative_removed)
print("Rows after:", after_negative)
print("Customers remaining:", clean_df["CustomerID"].nunique())

Rows before: 392732
Negative-quantity rows removed: 0
Rows after: 392732
Customers remaining: 4339

In [44]:
# Step 5: Remove non-positive UnitPrice transactions

before_price = len(clean_df)

invalid_price_mask = clean_df["UnitPrice"] <= 0
invalid_price_removed = invalid_price_mask.sum()

clean_df = clean_df[
    clean_df["UnitPrice"] > 0
].copy()

after_price = len(clean_df)

print("Rows before:", before_price)
print("Non-positive UnitPrice rows removed:", invalid_price_removed)
print("Rows after:", after_price)
print("Customers remaining:", clean_df["CustomerID"].nunique())

Rows before: 392732
Non-positive UnitPrice rows removed: 40
Rows after: 392692
Customers remaining: 4338

In [45]:
# Step 6: Remove postage/manual transaction types
# POST = postage
# DOT  = dotcom postage
# M    = manual entries

before_special_codes = len(clean_df)

special_codes = {"POST", "DOT", "M"}

special_code_mask = (
    clean_df["StockCode"]
    .astype(str)
    .isin(special_codes)
)

special_code_removed = special_code_mask.sum()

clean_df = clean_df[
    ~special_code_mask
].copy()

after_special_codes = len(clean_df)

print("Rows before:", before_special_codes)
print("POST/DOT/M rows removed:", special_code_removed)
print("Rows after:", after_special_codes)
print("Customers remaining:", clean_df["CustomerID"].nunique())

Rows before: 392692
POST/DOT/M rows removed: 1394
Rows after: 391298
Customers remaining: 4335

In [46]:
# Step 7: Final preprocessing validation

print("Final dataset shape:", clean_df.shape)
print()

print("Missing CustomerID:", clean_df["CustomerID"].isna().sum())
print("Duplicate rows:", clean_df.duplicated().sum())
print(
    "Cancelled invoices:",
    clean_df["InvoiceNo"].astype(str).str.startswith("C").sum()
)
print("Negative quantities:", (clean_df["Quantity"] < 0).sum())
print("Zero quantities:", (clean_df["Quantity"] == 0).sum())
print("Zero UnitPrice:", (clean_df["UnitPrice"] == 0).sum())
print("Negative UnitPrice:", (clean_df["UnitPrice"] < 0).sum())
print(
    "POST/DOT/M records:",
    clean_df["StockCode"].astype(str).isin({"POST", "DOT", "M"}).sum()
)

Final dataset shape: (391298, 8)

Missing CustomerID: 0
Duplicate rows: 0
Cancelled invoices: 0
Negative quantities: 0
Zero quantities: 0
Zero UnitPrice: 0
Negative UnitPrice: 0
POST/DOT/M records: 0

In [47]:
# Step 8: Preprocessing summary

preprocessing_summary = pd.DataFrame({
    "Stage": [
        "Raw dataset",
        "After duplicate removal",
        "After missing CustomerID removal",
        "After cancelled invoice removal",
        "After negative quantity treatment",
        "After non-positive UnitPrice removal",
        "After POST/DOT/M removal"
    ],
    "Rows": [
        541909,
        536641,
        401604,
        392732,
        392732,
        392692,
        391298
    ],
    "Customers": [
        4372,
        4372,
        4372,
        4339,
        4339,
        4338,
        4335
    ]
})

preprocessing_summary

                                  Stage    Rows  Customers
0                           Raw dataset  541909       4372
1               After duplicate removal  536641       4372
2      After missing CustomerID removal  401604       4372
3       After cancelled invoice removal  392732       4339
4     After negative quantity treatment  392732       4339
5  After non-positive UnitPrice removal  392692       4338
6              After POST/DOT/M removal  391298       4335

In [48]:
# Overall preprocessing reduction

initial_rows = 541909
final_rows = len(clean_df)

rows_removed = initial_rows - final_rows
percentage_removed = (rows_removed / initial_rows) * 100

print("Initial rows:", initial_rows)
print("Final rows:", final_rows)
print("Rows removed:", rows_removed)
print("Percentage removed:", round(percentage_removed, 2), "%")

Initial rows: 541909
Final rows: 391298
Rows removed: 150611
Percentage removed: 27.79 %

In [49]:
# Step 9: Create processed-data directory

from pathlib import Path

processed_dir = Path("../data/processed")
processed_dir.mkdir(parents=True, exist_ok=True)

print("Processed-data directory ready:", processed_dir)

Processed-data directory ready: ..\data\processed

In [50]:
# Step 10: Save cleaned transaction dataset

OUTPUT_PATH = processed_dir / "clean_transactions.csv"

clean_df.to_csv(OUTPUT_PATH, index=False)

print("Saved cleaned dataset to:")
print(OUTPUT_PATH)
print("Final shape:", clean_df.shape)

Saved cleaned dataset to:
..\data\processed\clean_transactions.csv
Final shape: (391298, 8)

In [51]:
# Step 11: Verify saved dataset

verified_df = pd.read_csv(OUTPUT_PATH)

print("Saved dataset shape:", verified_df.shape)
print("Missing CustomerID:", verified_df["CustomerID"].isna().sum())
print("Duplicate rows:", verified_df.duplicated().sum())
print("Negative quantities:", (verified_df["Quantity"] < 0).sum())
print("Non-positive UnitPrice:", (verified_df["UnitPrice"] <= 0).sum())

Saved dataset shape: (391298, 8)
Missing CustomerID: 0
Duplicate rows: 0
Negative quantities: 0
Non-positive UnitPrice: 0